extend type Exercise {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Exercise", purpose: IMPLICIT_KEY_FIELD)
}
extend type FitnessGoal {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "FitnessGoal", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `FitnessGoal`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "FitnessGoal.user", purpose: IMPLICIT_REF_FIELD)
}
extend type RoutineExercise {
  """
  ✨ Implicit foreign key field based on `RoutineExercise`.`workoutRoutine`. It must match the value of `WorkoutRoutine`.`id`. See `@ref` for how to customize it.
  """
  workoutRoutineId: UUID! @fdc_generated(from: "RoutineExercise.workoutRoutine", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `RoutineExercise`.`exercise`. It must match the value of `Exercise`.`id`. See `@ref` for how to customize it.
  """
  exerciseId: UUID! @fdc_generated(from: "RoutineExercise.exercise", purpose: IMPLICIT_REF_FIELD)
}
extend type User {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "User", purpose: IMPLICIT_KEY_FIELD)
}
extend type WorkoutExercise {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "WorkoutExercise", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `WorkoutExercise`.`exercise`. It must match the value of `Exercise`.`id`. See `@ref` for how to customize it.
  """
  exerciseId: UUID! @fdc_generated(from: "WorkoutExercise.exercise", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `WorkoutExercise`.`workoutSession`. It must match the value of `WorkoutSession`.`id`. See `@ref` for how to customize it.
  """
  workoutSessionId: UUID! @fdc_generated(from: "WorkoutExercise.workoutSession", purpose: IMPLICIT_REF_FIELD)
}
extend type WorkoutRoutine {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "WorkoutRoutine", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `WorkoutRoutine`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "WorkoutRoutine.user", purpose: IMPLICIT_REF_FIELD)
}
extend type WorkoutSession {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "WorkoutSession", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `WorkoutSession`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "WorkoutSession.user", purpose: IMPLICIT_REF_FIELD)
}
